import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { Footer } from "@/components/Footer"
import { Header } from "@/components/Header"
import { PageWrapper } from "@/components/PageWrapper"
import { Toaster } from "@/components/ui/sonner"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Mon E-commerce | Poto",
  description: "Generated by create babbbass",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = null
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} max-w-7xl antialiased flex flex-col items-center min-h-screen mx-auto p-2 md:px-5 gap-2 font-[family-name:var(--font-geist-sans)] bg-slate-50`}
      >
        <Header user={user} />
        <PageWrapper>{children}</PageWrapper>
        <Toaster closeButton />
        <Footer />
      </body>
    </html>
  )
}
